# Generated by Django 5.0.7 on 2026-07-29 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_email', models.EmailField(db_index=True, max_length=254)),
                ('visitor_phone', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('agenda', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='scheduled', max_length=16)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('google_meet_link', models.URLField(blank=True)),
                ('google_event_link', models.URLField(blank=True)),
                ('reschedule_count', models.PositiveIntegerField(default=0)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.CharField(blank=True, choices=[('visitor', 'Visitor'), ('admin', 'Admin')], max_length=16)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='meeting.meeting')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time', 'end_time', 'status'], name='meeting_mee_start_t_f5887f_idx'), models.Index(fields=['visitor_email', 'start_time'], name='meeting_mee_visitor_d10b74_idx')],
            },
        ),
    ]
